#cloud-config
autoinstall:
    source:
      id: ubuntu-desktop
    version: 1
    identity:
        realname: 'Ruan Rodrigues'
        hostname: ubuntu-rr
        username: ruan-rodrigues
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"
    packages:
        - libreoffice
        - gimp
        - git
        - maven
        - gnome-tweaks
        - neofetch
        - flatpak
        - vim
        - vlc
        - gnome-software-plugin-flatpak
        - folder-sushi
        - tree
        - firefox
        - curl
        - wget
        - gnome-shell-extension-manager
        - python3-venv
        - python3-poetry
        - python3-pip
    snaps:
        - name: spotify
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot

